name = "just-sticky-notes"
account_id = "e22a8e392dcb1319fcb607ca77401014"
workers_dev = true
main = "worker.js"
compatibility_date = "2025-01-01"

[build]
command = ""
[build.upload]
format = "service-worker"

# KV Namespace binding
[[kv_namespaces]]
binding = "just-sticky-notes-KV"
id = "c9765aa7285a402aa817b68cfddb1703"
preview_id = "c9765aa7285a402aa817b68cfddb1703"

# Environment variables
[vars]
ALLOWED_ORIGINS = "https://just-sticky-notes.lukems903.workers.dev,http://localhost:8080"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true